// tools/bumpFishVersion.js
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

function sha256hex(input) {
  return crypto.createHash("sha256").update(input).digest("hex");
}

function main() {
  const root = path.join(__dirname, "..");
  const fishPath = path.join(root, "fish.json");
  const outPath = path.join(root, "src", "fishVersion.ts");

  if (!fs.existsSync(fishPath)) {
    console.error(`fish.json not found at: ${fishPath}`);
    process.exit(1);
  }

  const fishText = fs.readFileSync(fishPath, "utf8");
  const hash = sha256hex(fishText).slice(0, 12);

  const out =
    `// Auto-generated by tools/bumpFishVersion.js\n` +
    `export const FISH_JSON_VERSION = "${hash}";\n`;

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out, "utf8");

  console.log(`FISH_JSON_VERSION = ${hash}`);
  console.log(`Wrote: ${outPath}`);
}

main();
