// Auto-generated by tools/bumpFishVersion.js
<<<<<<< HEAD
export const FISH_JSON_VERSION = "6e54c944f6fb";
=======
export const FISH_JSON_VERSION = "0c7407b413a3";
>>>>>>> 1b82361dcf3b1d7484482596130016f05ab758d5
